# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QDateEdit,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(220, 339)
        font = QFont()
        font.setFamilies([u"\ud568\ucd08\ub86c\ub3cb\uc6c0"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setCursor(QCursor(Qt.PointingHandCursor))
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.actionAlt_O = QAction(MainWindow)
        self.actionAlt_O.setObjectName(u"actionAlt_O")
        self.actionList_2 = QAction(MainWindow)
        self.actionList_2.setObjectName(u"actionList_2")
        self.actionList_3 = QAction(MainWindow)
        self.actionList_3.setObjectName(u"actionList_3")
        self.actionList_1 = QAction(MainWindow)
        self.actionList_1.setObjectName(u"actionList_1")
        self.actionList_4 = QAction(MainWindow)
        self.actionList_4.setObjectName(u"actionList_4")
        self.actionList_5 = QAction(MainWindow)
        self.actionList_5.setObjectName(u"actionList_5")
        self.actionList_6 = QAction(MainWindow)
        self.actionList_6.setObjectName(u"actionList_6")
        self.actionList_7 = QAction(MainWindow)
        self.actionList_7.setObjectName(u"actionList_7")
        self.actionList_8 = QAction(MainWindow)
        self.actionList_8.setObjectName(u"actionList_8")
        self.actionList_9 = QAction(MainWindow)
        self.actionList_9.setObjectName(u"actionList_9")
        self.actionList_10 = QAction(MainWindow)
        self.actionList_10.setObjectName(u"actionList_10")
        self.actionList_11 = QAction(MainWindow)
        self.actionList_11.setObjectName(u"actionList_11")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionVersion = QAction(MainWindow)
        self.actionVersion.setObjectName(u"actionVersion")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.run_btn = QPushButton(self.centralwidget)
        self.run_btn.setObjectName(u"run_btn")
        self.run_btn.setGeometry(QRect(30, 263, 75, 23))
        self.stop_btn = QPushButton(self.centralwidget)
        self.stop_btn.setObjectName(u"stop_btn")
        self.stop_btn.setGeometry(QRect(110, 263, 75, 23))
        self.dateStart = QDateEdit(self.centralwidget)
        self.dateStart.setObjectName(u"dateStart")
        self.dateStart.setGeometry(QRect(60, 103, 110, 22))
        self.dateStart.setLayoutDirection(Qt.LeftToRight)
        self.dateStart.setWrapping(True)
        self.dateStart.setFrame(True)
        self.dateStart.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setDate(QDate(2022, 11, 28))
        self.dateEnd = QDateEdit(self.centralwidget)
        self.dateEnd.setObjectName(u"dateEnd")
        self.dateEnd.setGeometry(QRect(60, 133, 110, 22))
        self.dateEnd.setWrapping(False)
        self.dateEnd.setProperty("showGroupSeparator", False)
        self.dateEnd.setCalendarPopup(True)
        self.scrape_comboBox = QComboBox(self.centralwidget)
        self.scrape_comboBox.addItem("")
        self.scrape_comboBox.addItem("")
        self.scrape_comboBox.addItem("")
        self.scrape_comboBox.addItem("")
        self.scrape_comboBox.setObjectName(u"scrape_comboBox")
        self.scrape_comboBox.setGeometry(QRect(60, 50, 76, 22))
        self.scrape_comboBox.setLayoutDirection(Qt.LeftToRight)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 102, 56, 21))
        font1 = QFont()
        font1.setFamilies([u"\ud568\ucd08\ub86c\ub3cb\uc6c0"])
        font1.setPointSize(11)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 56, 21))
        font2 = QFont()
        font2.setFamilies([u"\ud568\ucd08\ub86c\ub3cb\uc6c0"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.label_3.setFont(font2)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(30, 221, 181, 23))
        self.progressBar.setValue(57)
        self.progressBar.setOrientation(Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.browser_off = QRadioButton(self.centralwidget)
        self.browser_off.setObjectName(u"browser_off")
        self.browser_off.setGeometry(QRect(140, 183, 51, 16))
        self.browser_off.setAutoFillBackground(False)
        self.browser_off.setChecked(True)
        self.browser_on = QRadioButton(self.centralwidget)
        self.browser_on.setObjectName(u"browser_on")
        self.browser_on.setGeometry(QRect(80, 183, 51, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 132, 56, 21))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 180, 56, 21))
        font3 = QFont()
        font3.setFamilies([u"\ud568\ucd08\ub86c\ub3cb\uc6c0"])
        font3.setPointSize(10)
        font3.setBold(True)
        self.label_5.setFont(font3)
        self.list_option_comboBox = QComboBox(self.centralwidget)
        self.list_option_comboBox.addItem("")
        self.list_option_comboBox.addItem("")
        self.list_option_comboBox.addItem("")
        self.list_option_comboBox.setObjectName(u"list_option_comboBox")
        self.list_option_comboBox.setGeometry(QRect(60, 15, 76, 22))
        self.list_option_comboBox.setLayoutDirection(Qt.LeftToRight)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 15, 56, 21))
        self.label_6.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 220, 23))
        self.menurandom_values = QMenu(self.menubar)
        self.menurandom_values.setObjectName(u"menurandom_values")
        self.menuList_Open = QMenu(self.menurandom_values)
        self.menuList_Open.setObjectName(u"menuList_Open")
        self.menuList_Open.setFont(font)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuInfo = QMenu(self.menubar)
        self.menuInfo.setObjectName(u"menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menurandom_values.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menurandom_values.addAction(self.menuList_Open.menuAction())
        self.menurandom_values.addSeparator()
        self.menurandom_values.addAction(self.actionClose)
        self.menuList_Open.addAction(self.actionAlt_O)
        self.menuList_Open.addAction(self.actionList_2)
        self.menuList_Open.addAction(self.actionList_3)
        self.menuInfo.addAction(self.actionVersion)

        self.retranslateUi(MainWindow)

        self.scrape_comboBox.setCurrentIndex(0)
        self.list_option_comboBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAlt_O.setText(QCoreApplication.translate("MainWindow", u"List 1", None))
#if QT_CONFIG(shortcut)
        self.actionAlt_O.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+1", None))
#endif // QT_CONFIG(shortcut)
        self.actionList_2.setText(QCoreApplication.translate("MainWindow", u"List 2", None))
#if QT_CONFIG(shortcut)
        self.actionList_2.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+2", None))
#endif // QT_CONFIG(shortcut)
        self.actionList_3.setText(QCoreApplication.translate("MainWindow", u"List 3", None))
#if QT_CONFIG(shortcut)
        self.actionList_3.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+3", None))
#endif // QT_CONFIG(shortcut)
        self.actionList_1.setText(QCoreApplication.translate("MainWindow", u"List 1", None))
        self.actionList_4.setText(QCoreApplication.translate("MainWindow", u"List 2", None))
        self.actionList_5.setText(QCoreApplication.translate("MainWindow", u"List 3", None))
        self.actionList_6.setText(QCoreApplication.translate("MainWindow", u"List 1", None))
        self.actionList_7.setText(QCoreApplication.translate("MainWindow", u"List 2", None))
        self.actionList_8.setText(QCoreApplication.translate("MainWindow", u"List 3", None))
        self.actionList_9.setText(QCoreApplication.translate("MainWindow", u"List 1", None))
        self.actionList_10.setText(QCoreApplication.translate("MainWindow", u"List 2", None))
        self.actionList_11.setText(QCoreApplication.translate("MainWindow", u"List 3", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
#if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionVersion.setText(QCoreApplication.translate("MainWindow", u"Version", None))
        self.run_btn.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.stop_btn.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.scrape_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\uc120\ud0dd", None))
        self.scrape_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\ub9e4\ucd9c", None))
        self.scrape_comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\ub9ac\ubdf0", None))
        self.scrape_comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\uc815\uc0b0", None))

        self.scrape_comboBox.setCurrentText(QCoreApplication.translate("MainWindow", u"\uc120\ud0dd", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc791\uc77c", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uad6c\ubd84", None))
        self.browser_off.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.browser_on.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\uc885\ub8cc\uc77c", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\ube0c\ub77c\uc6b0\uc800", None))
        self.list_option_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"list_1", None))
        self.list_option_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"list_2", None))
        self.list_option_comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"list_3", None))

        self.list_option_comboBox.setCurrentText(QCoreApplication.translate("MainWindow", u"list_1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\ub9ac\uc2a4\ud2b8", None))
        self.menurandom_values.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuList_Open.setTitle(QCoreApplication.translate("MainWindow", u"Open List", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuInfo.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

